# syntax=docker/dockerfile:1
FROM rana921/link_hub:tagname
WORKDIR /LinkHub
# Install Redis client tools
# RUN apk update && apk add --no-cache redis

RUN apk add --no-cache openssl dos2unix

COPY ./compose-entrypoint.sh /compose-entrypoint.sh
RUN dos2unix /compose-entrypoint.sh

EXPOSE 3000
ENTRYPOINT ["sh", "/compose-entrypoint.sh"]

